{% set name = "aws-msk-iam-sasl-signer-python" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 853f69487517c9d38db638d69571fd8b9cc8d55913761accfc00950697aea975

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<38]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - click >=7.0
    - boto3 >=1.26.125
    - botocore >=1.29.125

test:
  source_files:
    - tests
  imports:
    - aws_msk_iam_sasl_signer
  requires:
    - pip
    - pytest
    - mock
  commands:
    - pip check
    - pytest -v

about:
  home: https://github.com/aws/aws-msk-iam-sasl-signer-python/
  summary: This library generates a signed url to enable authentication with an MSK Cluster.
  description: |
    This is an Amazon MSK Library in Python. 
    This library provides a function to generate a base 64 
    encoded signed url to enable authentication/authorization 
    with an MSK Cluster. The signed url is generated by using 
    your IAM credentials.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  dev_url: https://github.com/aws/aws-msk-iam-sasl-signer-python/
  doc_url: https://github.com/aws/aws-msk-iam-sasl-signer-python/blob/main/README.rst

extra:
  recipe-maintainers:
    - ViridianMelody
